- arguments: [--color, --cpp-define=HLINT]
- ignore: {name: "Use const" }
- ignore: {name: "Use camelCase" }
- ignore: {name: "Unused LANGUAGE pragma", within: [ FD.Monad ]}
- ignore: {name: "Parse error", within: [ Ref.Log ]}
- ignore: {name: "Eta reduce", within: [ Ref.Env, Ref.Key, Ref.Log ]}
