language: haskell
dist: trusty

cache:
  directories:
    - $HOME/.cabal/store

cabal: "2.4"

matrix:
  include:
    - os: linux
      env: GCC=/usr/bin/gcc-5
      ghc: "8.6.3"
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test

before_install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi
 - sudo update-alternatives --set gcc "$GCC"

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-configure
 - cabal v2-build
 - cabal v2-test --enable-test

notifications:
  irc:
    channels:
      - "irc.freenode.org##haskell-lens"
    skip_join: true
    template:
      - "\x0313guanxi\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
