language: haskell
dist: trusty

cache:
  directories:
    - $HOME/.cabal/store

cabal: "2.4"

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      ghc: "8.6.3"
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      ghc: "8.6.3"
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-configure --with-gcc=`which $(CC)`
 - cabal v2-build
 - cabal v2-test --enable-test

notifications:
  irc:
    channels:
      - "irc.freenode.org##haskell-lens"
    skip_join: true
    template:
      - "\x0313guanxi\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
